name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.LS_EC2_SSH_KEY }}

      - name: Deploy Django on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@52.15.114.254 "
            cd /home/ec2-user/LivestreamBackend &&
            git pull origin main &&
            source /home/ec2-user/your-venv/bin/activate &&
            cd streamapp &&
            pip install -r requirements.txt &&
            pkill -f 'gunicorn' || true &&
            nohup /home/ec2-user/LivestreamBackend/env/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 streamapp.wsgi:application > gunicorn.log 2>&1 &
          "